#!/usr/bin/env python3

import random

characters = [chr(c) for c in range(33, 127)]
secret_key = ''.join(random.choice(characters) for _ in range(64))
secret_key = secret_key.replace('\\', '\\\\')
secret_key = secret_key.replace('\'', '\\\'')

print(secret_key)
